from numpy.distutils.core import setup, Extension
from numpy import get_include
setup(name="gaepsi", version="1.0",
      package_dir = {'gaepsi': '.'},
      packages = [
        'gaepsi', 'gaepsi.cosmology', 'gaepsi.ccode', 'gaepsi.readers', 'gaepsi.tools', 'gaepsi.tools.sharedmem', 'gaepsi.cython'
      ],
      scripts = [ 'scripts/gadget-render.py', 
                  'scripts/gadget-mklayers.py', 
                  'scripts/gadget-hist.py',
                  'scripts/gadget-dump-header.py',
                  'scripts/gadget-check-file.py',
                  'scripts/gadget-gen-snapshot.py',
                  'scripts/gadget-crop-snapshot.py',
                 ],
      libraries=[('pluecker', {'sources':['ccode/pluecker.f90']}),
                 ],
      ext_modules = [
        Extension("gaepsi._gaepsiccode", 
             ["ccode/module.c", 
              "ccode/image.c", 
              "ccode/warp.c",
              "ccode/kernel.c",
              "ccode/peano.c",
              "ccode/render.c",
              "ccode/pmin.c",
              "ccode/camera.c",
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3', '-fopenmp'],
             libraries=['gomp', 'pluecker'],
             include_dirs=[get_include()],
             depends = ["ccode/defines.h"]
        ),
        Extension("gaepsi.cython._fast", 
             ["cython/_fast.c",],
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.cython._field", 
             ["cython/_field.c",],
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.cosmology._cosmology", 
             ["cosmology/_cosmology.c",],
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.cython.ztree", 
             ["cython/ztree.c", 
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O0 -g'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.cython.zquery", 
             ["cython/zquery.c", 
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O0 -g'],
             libraries=[],
             include_dirs=[get_include()],
             depends = ["cython/zquery_internal.c"]
        ),
        Extension("gaepsi.cython.zorder", 
             ["cython/zorder.c", 
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O0 -g'],
             libraries=[],
             include_dirs=[get_include()],
             depends = ["cython/zorder_internal.c"]
        ),
        Extension("gaepsi.cython._camera", 
             ["cython/_camera.c", 
             ], 
             extra_compile_args=['-g -O3'], 
#             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.tools.sharedmem.listtools", 
             ["tools/sharedmem/listtools.c", 
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
        Extension("gaepsi.tools.sharedmem._mergesort", 
             ["tools/sharedmem/mergesort.c", 
             ], 
#             extra_compile_args=['-g -O3'], 
             extra_compile_args=['-O3'],
             libraries=[],
             include_dirs=[get_include()],
        ),
      ])

