import SI

C = 3e5
G = 43007.1
H0 = 0.1

TIME_S = H0 / SI.H0
LENGTH_M = TIME_S * (SI.C / C)
MASS_KG = G / SI.G * LENGTH_M ** 3 * TIME_S ** -2

SOLARMASS = SI.SOLARMASS / MASS_KG
PROTONMASS = SI.PROTONMASS / MASS_KG
KPC = SI.KPC / LENGTH_M
MYEAR = SI.MYEAR / TIME_S
LYMAN_ALPHA_CROSSSECTION = SI.LYMAN_ALPHA_CROSSSECTION / (LENGTH_M**2)
#print 'GADGET.LENGTH_M', LENGTH_M
#print 'GADGET.MASS_KG', MASS_KG
#print 'GADGET.TIME_S', TIME_S


