import SI
pi = 3.1415926
C = 3e5
G = 43007.1
H0 = 0.1

TIME_S = H0 / SI.H0
LENGTH_M = TIME_S * (SI.C / C)
MASS_KG = G / SI.G * LENGTH_M ** 3 * TIME_S ** -2
TEMPERATURE_K = (LENGTH_M / TIME_S) ** 2 * SI.PROTONMASS / SI.BOLTZMANN
ENERGY_J = MASS_KG * (LENGTH_M / TIME_S) ** 2
POWER_W = ENERGY_J / TIME_S

SOLARMASS = SI.SOLARMASS / MASS_KG
SOLARLUMINOSITY = SI.SOLARLUMINOSITY / POWER_W

PROTONMASS = SI.PROTONMASS / MASS_KG

CM = 1. / (LENGTH_M * 100)
KPC = SI.KPC / LENGTH_M
MYEAR = SI.MYEAR / TIME_S

LYMAN_ALPHA_CROSSSECTION = SI.LYMAN_ALPHA_CROSSSECTION / (LENGTH_M**2)
RYDBERG = SI.RYDBERG / ENERGY_J
CRITICAL_DENSITY = 3 * H0 ** 2/ (8 * pi * G)
#print 'GADGET.LENGTH_M', LENGTH_M
#print 'GADGET.MASS_KG', MASS_KG
#print 'GADGET.TIME_S', TIME_S


